source 'http://rubygems.org'

gem 'rails', '3.1.0'
gem 'sqlite3', '1.3.4'
gem 'gravatar_image_tag', '1.0.0.pre2'
gem 'will_paginate', '3.0.pre2'

# Asset template engines
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'

gem 'jquery-rails'

group :development do
  gem 'rspec-rails', '2.6.1'
 gem 'annotate', '2.4.1.beta1'
 gem 'faker', '0.3.1'
end


group :production do
  gem 'therubyracer-heroku', '0.8.1.pre3' # you will need this too
  gem 'pg'
end
