source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

gem 'execjs'
gem 'therubyracer'
# mise en forme des donnees dans la console ruby
gem 'hirb'
gem 'jquery-rails'
# authentification
gem 'devise'
# système d'authorisation avec roles'
gem 'cancan'
# Avatar
gem 'paperclip', '~> 2.4'
# Bitmasks
gem 'bitmask_attributes'

group :development do
    gem 'annotate', '2.4.1.beta1'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

