source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'formtastic'
gem 'execjs'
gem 'therubyracer'
gem 'jquery-rails'

# Gemfile in Rails >= 3.1
gem 'activeadmin'
gem 'sass-rails'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'sqlite3'
end